# config/services.yaml
services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
        
    App\Service\ExampleService: ~


    # Example service
    App\Service\ExampleService:
        arguments:
            $someArgument: 'value'

    # LoginFormAuthenticator service
    App\Security\LoginFormAuthenticator:
        arguments:
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'